### ISSUE TITLE
chat time resetting

### ISSUE THREAD

**Issue by TALON56** [LuckehPickle/Comet#20] opened 2016-05-20 04:16 UTC
conversation times do not properly save. once putting my computer to sleep and refreshing the page on return i was greeted with this 
![image](https://cloud.githubusercontent.com/assets/17866451/15417078/5cf08d84-1e95-11e6-9169-b79b9eb76bc1.png) rather than the 10:41 that the conversation took place in

**Comment by LuckehPickle** [comment] 2016-05-20 04:19
Duplicate of #6

**Closed** 2016-05-20 04:20 UTC
Labels: bug, duplicate
